version: "3"
services:
  influxdb:
    image: influxdb:1.6
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /data/influxdb/data:/var/lib/influxdb
  rabbitmq:
    image: rabbitmq:3.7.7-management
    hostname: "lecole-rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
