version: "2"
services:
  api:
    build: ./api
    ports:
      - "4251:4251"
    depends_on:
      - db
  db:
    image: timescale/timescaledb:latest-pg11
    ports:
      - "5432:5432"
    volumes:
      - /data/timescale:/var/lib/postgresql/data
