version: "3"
services:
  influxdb:
    image: influxdb:1.6
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /data/influxdb:/var/lib/influxdb
    restart: always
  rabbitmq:
    image: rabbitmq:3.7.7-management
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
    restart: always
  scribe:
    build: ./scribe
    depends_on:
      - "influxdb"
      - "rabbitmq"
    environment:
      WAIT_HOSTS: rabbitmq:5672, influxdb:8086
