version: "3.7"
services:
  influxdb:
    image: influxdb:1.7-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /data/influxdb:/var/lib/influxdb
    restart: always
  api:
    build: ./api
    env_files:
      - /data/api/api.env
