---
- hosts: sky
  become: yes
  vars:
    project_path: /opt/memory-station
    node_version: "12"
    ansible_distribution_release: "bionic"
  tasks:
    - name: Ensure apt-transport-https is installed
      apt:
        name: apt-transport-https

    - name: add apt key for nodesource
      apt_key: 
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: add repo for nodesource
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release  }} main' 
        state: present
        update_cache: yes

    - name: install nodejs
      apt: 
        name: nodejs
        update_cache: yes

    - name: Add Yarn apt key
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg

    - name: Add Yarn repository
      apt_repository:
        repo: "deb https://dl.yarnpkg.com/debian/ stable main"
        filename: yarn

    - name: Install Yarn
      apt:
        name: yarn

    - name: copy app file
      copy: src=../api.js dest={{ project_path }} force=yes

    - name: copy package.json
      copy: src=../package.json dest={{ project_path }} force=yes

    - name: copy pm2 process.json
      copy: src=../process.json dest={{ project_path }} force=yes

    - name: install pm2
      npm:
        name: pm2
        state: present
        global: yes
        production: yes

    - name: update dependencies
      yarn:
        path: "{{ project_path }}"

    - name: start pm2 process
      command: pm2 start {{ project_path }}/process.json
      ignore_errors: yes
