---
- hosts: sky
  become: yes
  vars:
    project_path: /opt/memory-station
  tasks:
    - name: enable SSH forwarding for sudo
      lineinfile:
        dest: /etc/sudoers
        insertafter: '^#?\s*Defaults\s+env_keep\b'
        line: 'Defaults    env_keep += "SSH_AUTH_SOCK"'
    - name: clone repository
      git:
        repo: git@github.com:jzlou/memory-station.git
        dest: "{{ project_path }}"
    - name: update dependencies
      yarn:
        path: "{{ project_path }}"
    - name: delete previous pm2 process
      command: pm2 delete memory-station
      ignore_errors: yes
    - name: start pm2 process
      command: pm2 start {{ project_path }}/process.json
